apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-deployment
    labels:
        app: devops-week3
spec:
    replicas: 1
    selector:
        matchLabels:
            app: devops
    template:
        metadata:
            labels:
                app: devops
        spec:
            containers:
                - name: week3
                  image: fredamoako/devops
                  ports:
                      - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-service
spec:
    selector:
        app: devops
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8083
          targetPort: 8083
          nodePort: 30000
